version: '3.9'
services:
  server:
    build:
      context: ./api
    ports:
      - "80:5000"
    volumes:
      - ./api:/app  # Change this line to point directly to the api directory
    environment:
      FLASK_ENV: development
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/user/src/app
    depends_on:
      - server
